#!/bin/bash

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

for F in $(git diff --cached --name-only | grep ".docx$"); do
	if [ -f $F ]; then
	   echo "$F";
	   unzip "$F" -d "${F%.*}..docx/" && rm "$F";
	   mv "${F%.*}..docx" "$F";
	   find "$F" -name "*.xml" -type f -exec sed -i '' $'s/\/>/\/>\\\n/g' {} \;
	   find "$F" -name "*.xml" -type f -exec sed -i '' '/^$/d' {} \;
	   git add "$F"
	fi
done

IFS=$SAVEIFS
